repo: con/tinuous
ci:
  github:
    path: 'logs/{year}/{month}/{day}/{ci}/{type}/{type_id}/{commit}/{wf_name}/{number}/'
    workflows:
      - test.yml
  travis:
    path: 'logs/{year}/{month}/{day}/{ci}/{type}/{type_id}/{commit}/{number}/{job}.txt'
since: 2021-02-01T00:00:00Z
types: [cron, pr, push]
